name: build-validate-publish

# This workflow runs on pull requests and pushes to the main branch, and
# builds/validates the specs, other documents, and supplemental materials.
# This includes verifying the WGSL grammar which is one of the generated
# supplemental materials.
#
# On pushes to the main branch, it also publishes the outputs to GitHub Pages.

on:
  pull_request:
  push:
    branches: [main]
  # Allows admins to trigger the workflow manually from GitHub's UI.
  workflow_dispatch:

jobs:
  # Note, spec-prod can publish to gh-pages as well, but we use a custom publish
  # step to publish additional files anyway, so we use that instead of making
  # many separate gh-pages commits (one per bikeshed file + one for extras).
  build-validate-publish:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Prepare OS
        run: |
          sudo apt update
          sudo apt install -y locales
          sudo locale-gen en_US.UTF-8
          sudo apt install -y git libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 python3-full python3-pip rsync
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16
          nvm use 16
          
      - uses: actions/checkout@v3

      - name: Build and validate
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          export PATH="$(python3 -m site --user-base)/bin:${PATH}"
          bash tools/install-dependencies.sh bikeshed wgsl diagrams
          BIKESHED_DISALLOW_ONLINE=1 REQUIRE_DIAGRAM_GENERATION=1 make -j out
          # Ensure diagrams didn't change after regeneration
          bash tools/check-repo-clean.sh

      - name: Deploy to GitHub Pages
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: out
