name: Publish static files to GitHub Pages

# Workflow runs on pushes to the main branch. It publishes statics files to
# GitHub Pages. The specs themselves (WebGPU, WGSL, the explainer) are handled
# separately in a different workflow.
# The "workflow_dispatch" hook allows admins to trigger the workflow manually
# from GitHub's UI.

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy static files to the "out" folder
        run: |
          export PATH="$(python3 -m site --user-base)/bin:${PATH}"
          mkdir ./out
          ./compile.sh static

      - name: Deploy to GitHub Pages
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: out
          CLEAN-EXCLUDE: |
            index.html
            wgsl/index.html
            explainer/index.html
