name: Build and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build with bikeshed
        run: |
          git clone --depth 1 https://github.com/tabatkins/bikeshed.git
          pip3 install --user --editable ./bikeshed
          export PATH="$(python3 -m site --user-base)/bin:${PATH}"
          bikeshed update
          mkdir out
          ./compile.sh

      - name: Archive build ouput as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rendered
          path: out/

      - name: Deploy to GitHub Pages (only on main branch)
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
